version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    env_file:
      - ./frontend/frontend.env

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    working_dir: /app
    ports:
      - "3002:3002"
    depends_on:
      - auth-db
    env_file:
      - ./backend/auth-service/auth.env

  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    working_dir: /app
    ports:
      - "3003:3003"
    depends_on:
      - notification-db
    env_file:
      - ./backend/notification-service/notification.env

  task-service:
    build:
      context: ./backend/task-service
      dockerfile: Dockerfile
    container_name: task-service
    working_dir: /app
    ports:
      - "3004:3004"
    depends_on:
      - task-db
    env_file:
      - ./backend/task-service/task.env

  auth-db:
    image: mysql:5.7
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: Brds-2024
      MYSQL_DATABASE: auth_database
    ports:
      - "3307:3306"
    volumes:
      - auth_db_data:/var/lib/mysql

  notification-db:
    image: mysql:5.7
    container_name: notification-db
    environment:
      MYSQL_ROOT_PASSWORD: Brds-2024
      MYSQL_DATABASE: notification_database
    ports:
      - "3308:3306"
    volumes:
      - notification_db_data:/var/lib/mysql

  task-db:
    image: mysql:5.7
    container_name: task-db
    environment:
      MYSQL_ROOT_PASSWORD: Brds-2024
      MYSQL_DATABASE: taskit_database
    ports:
      - "3309:3306"
    volumes:
      - task_db_data:/var/lib/mysql

volumes:
  auth_db_data:
  notification_db_data:
  task_db_data: